version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=your_jwt_secret
      - STRIPE_SECRET_KEY=sk_test_xxx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000