services:
  - type: web
    name: ecommerce-backend
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Add other env vars in Render dashboard (JWT_SECRET, STRIPE_SECRET_KEY, etc.)